package com.live.humanmesh.model

data class SignupBody(
    val account_public: String,
    val country_code: String,
    val createdAt: String,
    val device_token: String,
    val device_type: String,
    val dob: String,
    val email: String,
    val event_details_show: String,
    val gender: String,
    val id: Int,
    val interest_show: String,
    val is_delete: String,
    val is_notification: String,
    val is_verify: String,
    val latitude: String,
    val location: String,
    val login_time: Int,
    val longitude: String,
    val name: String,
    val nick_name: String,
    val nick_name_show: String,
    val otp: Int,
    val password: String,
    val phone_number: String,
    val photo_visiblity: String,
    val role: String,
    val social_type: String,
    val status: String,
    val token: String,
    val updatedAt: String
)